In [66]:
def home_made_list_generator(dimensions, a):
    pass

In [67]:
import numpy as np

#  simple 2d transpose

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a_np = np.array(a)
b_np = np.array(b)

# Normal
print(a_np)
print(b_np)
print()
# Transposed version
print(a_np.T)
print(b_np.T)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]



In [68]:
#  simple 3d transpose

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a_np = np.array(a)
b_np = np.array(b)

# Normal
print(a_np)
print(b_np)
print()
# Transposed version
print(a_np.T)
print(b_np.T)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]



In [69]:
import numpy as np

a1 = np.arange(1, 13)  # numbers 1 to 12print(a1.shape)
print(a1)
a1_2d = a1.reshape(3, 4)  # 3_4
print(a1_2d.shape)
print(a1_2d)

print(a1.reshape(3, 4))
print(a1.reshape(-1, 4))  # same as above: a1.reshape(3, 4)a1.reshape(3, 4)
print(a1.reshape(3, -1))  # same as above: a1.reshape(3, 4)a1.reshape(2, 6)

print(a1.reshape(2, -1))  # same as above: a1.reshape(2, 6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [70]:
print(a1.reshape(3, 4)) # reshapes or ‘fills in’ row by row
print(a1.reshape(3, 4, order='C')) # same results as above

print(a1.reshape(3, 4, order='F'))# reshapes column by column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [71]:

print(a1.reshape(3, 2, 2)) # reshapes or ‘fills in’ row by row
print(a1.reshape(3, 2, 2, order='C')) # same results as above

print(a1.reshape(3, 2, 2, order='F'))# reshapes column by column

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [72]:
# Understand and manufacture a pic

red = np.ones((28, 28))
green = np.ones((28, 28))*2
blue = np.ones((28, 28))*3

attempt1 = np.concatenate([red, green, blue])

attempt2 = np.concatenate([i.reshape(-1, 28,28) for i in [red, green, blue]])
attempt2_final = attempt2.reshape(28, 28, 3)
attempt2_final2 = attempt2.reshape(28, 28, 3, order="F")

transpose_1 = attempt2.transpose(0,1,2)
transpose_2 = attempt2.transpose(1,2,0)
transpose_3 = attempt2.transpose(2,0,1)

# print image in red
print(transpose_2[:,:,0])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1

In [73]:
# generate more interesting pic
image = np.concatenate([np.arange((chanel*28*28), (chanel+1)*28*28).reshape(-1, 28, 28) for chanel in range(3)])
print(image.transpose(1,2,0)[:,:,0])

image_like_eval5 = image.transpose(1,2,0)

# create a small dataset
dataset = np.concatenate([image_like_eval5.reshape(-1, 28, 28, 3)+28*28*i*3 for i in range(0,10)])
print(dataset[0, :, :,0])
print(dataset.transpose(0, 3, 1, 2))
# multiple chanels multiple images
stacked_channels_dataset_primer = dataset.transpose(0, 3, 1, 2)
stacked_channels_dataset = stacked_channels_dataset_primer.reshape(10*3,28,28,-1)
stacked_channels_dataset_simplified = stacked_channels_dataset_primer.reshape(10*3,28,28)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
   46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
   74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
  102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
  130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
  186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213
  214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 23

In [75]:
from si.util.im2col import im2col, col2im

values, index = im2col(stacked_channels_dataset, (2,2,1,1),0,2)
max_pool = np.amax(values, axis=0)
values_a = max_pool.reshape(30,-1, order="F")
values_b = max_pool.reshape(30,14,14, order="F")
values_c = max_pool.reshape(10,3,14,14, order="F")
values_d = max_pool.reshape(10,3,14,14)
values_e = max_pool.reshape(10,14,14,3)
values_f = max_pool.reshape(10,14,14,3, order="F")

primer_recomposed = max_pool.reshape(30,14,14,-1, order="F")
recomposed = primer_recomposed.transpose(0, 3, 2, 1)
recompose_correct_dim = recomposed.reshape(10,3,14,14)
recomposed2 = primer_recomposed.transpose(0, 2, 1, 3)

primer_recomposed2 = max_pool.reshape(10,3,14,14, order="F")
recomposed3 = primer_recomposed2.transpose(0, 2, 3, 1).reshape(10,14,-1)
recomposed4 = primer_recomposed2.transpose(0, 3, 2, 1).reshape(10,14,-1)

primer_recomposed3 = max_pool.reshape(10,3,14,14)
recomposed5 = primer_recomposed3.transpose(0, 2, 3, 1).reshape(10,14,14,-1)
recomposed51 = primer_recomposed3.transpose(0, 2, 3, 1)
recomposed6 = primer_recomposed3.transpose(0, 3, 2, 1).reshape(10,14,14,-1)
recomposed61 = primer_recomposed3.transpose(0, 3, 2, 1)

primer_recomposed4 = max_pool.reshape(10, 14, 14, 3)
recomposed7 = primer_recomposed4.transpose(0, 2, 3, 1)

primer_recomposed5 = max_pool.reshape((14*14), 10, -1)
primer_recomposed5 = max_pool.reshape((14*14), -1)
primer_recomposed6 = max_pool.reshape(10, (14*14), -1)
primer_recomposed7 = max_pool.reshape(10, -1)

# recomposed7 = primer_recomposed7.transpose(0, 2, 1, 3)
a = recomposed7.reshape(10, 14,-1)

primer_recomposed23 = max_pool.reshape((14*14), -1)
primer_recomposed23 = primer_recomposed23.T
primer_recomposed23 = primer_recomposed23.reshape(10*3,14,14,-1)
primer_recomposed23 = primer_recomposed23.transpose(0, 3, 1, 2)
primer_recomposed23 = primer_recomposed23.reshape(10,3,14,14)
primer_recomposed23 = primer_recomposed23.transpose(0, 2, 3, 1)

primer_recomposed32 = primer_recomposed23.transpose(0, 3, 2, 1)
primer_recomposed32 = primer_recomposed32.reshape(10*3,14,14)
primer_recomposed32 = primer_recomposed32.T
primer_recomposed32 = primer_recomposed32.ravel()

pool_max = primer_recomposed32

np.equal(max_pool, pool_max).all()

True